sdrf:
  - "sdrf.txt"
condensed_sdrf:
  - "condensed-sdrf.tsv"
datasets:
  - "E-GEOD-DUMMY"
  - "E-ENAD-27"
  - "E-GEOD-81608"
scxa_classifiers_prefix:
  - "http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/sc_experiments_classifiers"
scxa_experiments_prefix: 
  - "http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/sc_experiments"
tool_perf_table:
  - "https://www.ebi.ac.uk/~a_solovyev/prod_testing_data/tool_perf_pvals.tsv"

