datasets:
  - "E-ENAD-27"
  - "E-GEOD-81608"
scxa_classifiers_prefix:
  - "ftp://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/sc_experiments_classifiers"
scxa_experiments_prefix: 
  - "ftp://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/sc_experiments"